manifest_version = 2
name = "Redirect old URLs at the edge"
description = ""
authors = ["<oss@fastly.com>"]
language = "javascript"

[local_server.backends.origin_0]
  url = "https://httpbin.org"

[setup.backends.origin_0]
address = "httpbin.org"
port = 443
